"""Configuration values for the Webots RosBot navigation project."""

MODE = "RUN"
TARGET_MODE = "BLUE_ONLY"
TIME_STEP = 32

WHEEL_RADIUS_M = 0.055
TRACK_WIDTH_M = 0.32
ROBOT_RADIUS_M = 0.23
SAFETY_MARGIN_M = 0.06

MOTOR_FORWARD_SIGN = 1.0
MOTOR_TURN_SIGN = 1.0

MAX_LINEAR_SPEED = 0.70
MAX_ANGULAR_SPEED = 2.00
MAX_WHEEL_SPEED = 18.0

SEARCH_ROTATION_SPEED = 0.65
NO_PATH_ROTATION_SPEED = 0.65
VISUAL_APPROACH_FAST_MPS = 0.45
VISUAL_APPROACH_SLOW_MPS = 0.16
VISUAL_APPROACH_ALIGN_ERROR = 0.55

VISUAL_SERVO_ANGULAR_GAIN = 0.55
VISUAL_SERVO_DEADBAND = 0.035

LIDAR_SELF_OCCLUSION_ANGLE_MIN_RAD = 0.1047
LIDAR_SELF_OCCLUSION_ANGLE_MAX_RAD = 1.658

GRID_RESOLUTION_M = 0.05
MAP_WIDTH_M = 20.0
MAP_HEIGHT_M = 20.0
MAP_ORIGIN_X = -MAP_WIDTH_M / 2.0
MAP_ORIGIN_Z = -MAP_HEIGHT_M / 2.0

UNKNOWN = -1
FREE = 0
OBSTACLE = 1
FORBIDDEN_GREEN = 2
OBSTACLE_INFLATION_M = ROBOT_RADIUS_M + SAFETY_MARGIN_M

WAYPOINT_TOLERANCE_M = 0.24
GOAL_TOLERANCE_M = 0.35
REPLAN_INTERVAL_S = 0.7
FRONTIER_MIN_CLUSTER_SIZE = 4
FRONTIER_BEARING_WEIGHT = 40.0
FRONTIER_MAX_RETRIES = 8
MAX_VISITED_WAYPOINTS = 40

DWA_DT = 0.10
DWA_PREDICTION_TIME = 1.0
DWA_LINEAR_SAMPLES = 6
DWA_ANGULAR_SAMPLES = 11
DWA_GOAL_WEIGHT = 2.2
DWA_CLEARANCE_WEIGHT = 0.7
DWA_SPEED_WEIGHT = 0.8
DWA_PATH_WEIGHT = 0.7

BLUE_HSV_LOW = (100, 55, 45)
BLUE_HSV_HIGH = (125, 255, 255)
YELLOW_HSV_LOW = (15, 70, 50)
YELLOW_HSV_HIGH = (40, 255, 255)
GREEN_HSV_LOW = (45, 70, 50)
GREEN_HSV_HIGH = (85, 255, 255)

MIN_COLOR_AREA = 100
TARGET_REACHED_AREA = 8500
TARGET_REACHED_MAX_ERROR = 0.32

PRINT_EVERY_N_STEPS = 10
DEBUG_SHOW_GREEN_MARKS = False
DEBUG_PLANNING = False
DEBUG_VISUAL_SERVO = True
DEBUG_MOTOR_COMMANDS = True

PHYSICS_JUMP_MULTIPLIER = 4.0
STUCK_POSITION_EPSILON_M = 0.05
STUCK_TIME_THRESHOLD_S = 4.0
